# Generated by Django 4.0.5 on 2022-11-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=500)),
                ('CustomerEmail', models.CharField(max_length=500)),
                ('CustomerOrders', models.CharField(max_length=500)),
                ('CustomerPassword', models.CharField(max_length=20)),
                ('CustomerDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ProductType', models.CharField(max_length=500)),
                ('ProductBrand', models.CharField(max_length=500)),
                ('ProductDetails', models.CharField(max_length=1000)),
                ('price', models.IntegerField(max_length=100)),
                ('ProductCount', models.IntegerField(max_length=500)),
                ('ProductImage', models.CharField(max_length=500)),
            ],
        ),
    ]
